import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> results: "";
    in-out property <bool> curtain;
    callback divide-income(string);

    background: #2d2929;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Income Divider";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter the Income";
                height: 35px;
            }

        }
        Row {
            Button {
                text: "Calculate";
                primary: true;
                padding-top: 30px;
                height: 35px;
                clicked => {
                    root.curtain = !root.curtain;
                    divide-income(income.text);
                }
            }

        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                    Rectangle {
                        background: #333333;
                        x: 0;
                        width: curtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                             duration: 250ms; easing: ease-in;
                        }
                    }
                    Rectangle {
                        background: #333333;
                        x: curtain ? parent.width : parent.width / 2;
                        width: curtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                             duration: 250ms; easing: ease-in;
                        }
                        animate x {
                             duration: 250ms; easing: ease-in;
                        }
                    }
                }
            }
        }
    }
}
